#!/usr/bin/env python3
"""
abi swarm - Main Application
ABI Swarm - Self-Building Multi-Agent System

Domain: general
Generated by ABI-Core CLI
"""

import os
import json
import asyncio
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, List, Optional

import uvicorn
from fastapi import FastAPI, HTTPException, Depends
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from config.config import config
from abi_core.common.utils import abi_logging

# Lifespan context manager (replaces deprecated on_event)
from contextlib import asynccontextmanager

@asynccontextmanager
async def lifespan(app: FastAPI):
    """Application lifespan - startup and shutdown"""
    
    # Startup
    abi_logging(f"🚀 Starting abi swarm")
    abi_logging(f"📋 Description: ABI Swarm - Self-Building Multi-Agent System")
    abi_logging(f"🏷️ Domain: general")
    abi_logging(f"⚙️ Configuration: {config.to_dict()}")
    
    
    # Test semantic layer connection
    try:
        agents = await semantic_client.call("find_agent", query="list all")
        abi_logging(f"✅ Semantic layer connected - {len(agents)} agents registered")
    except Exception as e:
        abi_logging(f"⚠️ Semantic layer connection failed: {e}", level="warning")
    
    
    
    # Test guardian connection
    try:
        import httpx
        async with httpx.AsyncClient() as client:
            response = await client.get(
                f"http://{config.guardian_host}:{config.guardian_port}/health",
                timeout=5.0
            )
            if response.status_code == 200:
                abi_logging("✅ Guardian security service connected")
            else:
                abi_logging(f"⚠️ Guardian service returned {response.status_code}", level="warning")
    except Exception as e:
        abi_logging(f"⚠️ Guardian connection failed: {e}", level="warning")
    
    
    yield  # Application runs here
    
    # Shutdown
    abi_logging("🛑 Shutting down abi swarm")

# FastAPI app with lifespan
app = FastAPI(
    title="abi swarm",
    description="ABI Swarm - Self-Building Multi-Agent System",
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
    lifespan=lifespan
)

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Pydantic models
class AgentRequest(BaseModel):
    query: str
    context: Optional[Dict[str, Any]] = None

class AgentResponse(BaseModel):
    agent_id: Optional[str]
    agent_name: Optional[str]
    response: str
    metadata: Dict[str, Any]


from abi_core.common.semantic_tools import MCPToolkit
from abi_core.common.service_card import ServiceCard

# Load service card for MCP authentication
_service_card_path = os.getenv(
    'SERVICE_CARD',
    str(Path(__file__).parent / 'service_cards' / 'webapp.json')
)
try:
    _service_card = ServiceCard.from_file(_service_card_path)
    abi_logging(f"✅ Service card loaded: {_service_card.name}")
except Exception as e:
    abi_logging(f"⚠️ No service card at {_service_card_path}: {e}", level="warning")
    _service_card = None

# Initialize semantic layer client via MCPToolkit with service identity
semantic_client = MCPToolkit(service_card=_service_card)



class GuardianClient:
    """Client for guardian security service"""
    
    def __init__(self):
        # guardian_host puede incluir http://, verificar para no duplicar
        if hasattr(config, 'guardian_url') and config.guardian_url:
            self.base_url = config.guardian_url
        else:
            if config.guardian_host.startswith('http://') or config.guardian_host.startswith('https://'):
                self.base_url = config.guardian_host
            else:
                self.base_url = f"http://{config.guardian_host}:{config.guardian_port}"
        
    async def validate_access(self, agent_id: str, agent_card: Dict[str, Any], 
                            request_metadata: Dict[str, Any] = None) -> Dict[str, Any]:
        """Validate agent access via Guardian"""
        import httpx
        
        try:
            async with httpx.AsyncClient() as client:
                response = await client.post(
                    f"{self.base_url}/v1/tools/validate_semantic_access",
                    json={
                        "agent_id": agent_id,
                        "agent_card": agent_card,
                        "request_metadata": request_metadata or {}
                    },
                    timeout=10.0
                )
                
                if response.status_code == 200:
                    return response.json()
                else:
                    abi_logging(f"Guardian error: {response.status_code}", level="error")
                    return {
                        "allowed": False,
                        "reason": f"Guardian service error: {response.status_code}",
                        "risk_score": 1.0
                    }
                    
        except Exception as e:
            abi_logging(f"Error contacting Guardian: {e}", level="error")
            return {
                "allowed": False,
                "reason": f"Guardian service unavailable: {str(e)}",
                "risk_score": 1.0
            }

# Initialize guardian client
guardian_client = GuardianClient()


# Routes
@app.get("/")
async def root():
    """Root endpoint with service information"""
    return {
        "service": "abi swarm",
        "description": "ABI Swarm - Self-Building Multi-Agent System",
        "domain": "general",
        "version": "1.0.0",
        "status": "running",
        "timestamp": datetime.utcnow().isoformat(),
        "config": {
            "abi_role": config.abi_role,
            "abi_node": config.abi_node,
            "model_name": config.model_name,
            
            "semantic_layer": f"{config.semantic_layer_host}:{config.semantic_layer_port}",
            
            
            "guardian_security": f"{config.guardian_host}:{config.guardian_port}",
            
        }
    }

@app.get("/health")
async def health():
    """Health check endpoint"""
    health_status = {
        "status": "healthy",
        "service": "abi swarm",
        "timestamp": datetime.utcnow().isoformat(),
        "checks": {}
    }
    
    
    # Semantic layer status is reported but NOT checked on every health poll
    # to avoid excessive MCP connections and memory leaks
    health_status["checks"]["semantic_layer"] = {
        "status": "configured",
        "host": f"{config.semantic_layer_host}:{config.semantic_layer_port}"
    }
    
    
    
    # Check guardian
    try:
        import httpx
        async with httpx.AsyncClient() as client:
            response = await client.get(
                f"http://{config.guardian_host}:{config.guardian_port}/v1/tools/get_guardian_status",
                timeout=5.0
            )
            if response.status_code == 200:
                health_status["checks"]["guardian"] = {
                    "status": "healthy",
                    "details": response.json()
                }
            else:
                health_status["checks"]["guardian"] = {
                    "status": "unhealthy",
                    "error": f"HTTP {response.status_code}"
                }
                health_status["status"] = "degraded"
    except Exception as e:
        health_status["checks"]["guardian"] = {
            "status": "unhealthy",
            "error": str(e)
        }
        health_status["status"] = "degraded"
    
    
    return health_status

@app.get("/v1/config")
async def get_config():
    """Get current configuration"""
    return config.to_dict()


@app.get("/v1/agents")
async def list_agents():
    """List all registered agents"""
    try:
        agents = await semantic_client.call("find_agent", query="list all")
        return {
            "agents": agents,
            "total": len(agents),
            "timestamp": datetime.utcnow().isoformat()
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error listing agents: {str(e)}")

@app.post("/v1/agents/find", response_model=AgentResponse)
async def find_agent(request: AgentRequest):
    """Find the best agent for a given query"""
    try:
        # Find agent via semantic layer
        agent_card = await semantic_client.call("find_agent", query=request.query)
        
        if not agent_card:
            return AgentResponse(
                agent_id=None,
                agent_name=None,
                response=f"No suitable agent found for query: {request.query}",
                metadata={
                    "query": request.query,
                    "found": False,
                    "timestamp": datetime.utcnow().isoformat()
                }
            )
        
        
        # Validate access via Guardian
        validation_result = await guardian_client.validate_access(
            agent_id=agent_card.get("id", "unknown"),
            agent_card=agent_card,
            request_metadata={
                "query": request.query,
                "method": "find_agent",
                "source_ip": "internal",
                "user_agent": "abi swarm"
            }
        )
        
        if not validation_result.get("allowed", False):
            return AgentResponse(
                agent_id=agent_card.get("id"),
                agent_name=agent_card.get("name"),
                response=f"Access denied by Guardian: {validation_result.get('reason', 'Unknown reason')}",
                metadata={
                    "query": request.query,
                    "found": True,
                    "access_denied": True,
                    "risk_score": validation_result.get("risk_score", 1.0),
                    "guardian_validation": validation_result,
                    "timestamp": datetime.utcnow().isoformat()
                }
            )
        
        
        return AgentResponse(
            agent_id=agent_card.get("id"),
            agent_name=agent_card.get("name"),
            response=f"Found agent: {agent_card.get('name')} - {agent_card.get('description')}",
            metadata={
                "query": request.query,
                "found": True,
                "agent_card": agent_card,
                
                "guardian_validation": validation_result,
                
                "timestamp": datetime.utcnow().isoformat()
            }
        )
        
    except Exception as e:
        abi_logging(f"Error in find_agent: {e}", level="error")
        raise HTTPException(status_code=500, detail=f"Error finding agent: {str(e)}")





@app.get("/v1/security/status")
async def get_security_status():
    """Get security status from Guardian"""
    try:
        import httpx
        async with httpx.AsyncClient() as client:
            response = await client.get(
                f"http://{config.guardian_host}:{config.guardian_port}/v1/tools/get_security_metrics",
                timeout=10.0
            )
            
            if response.status_code == 200:
                return response.json()
            else:
                raise HTTPException(status_code=response.status_code, detail="Guardian service error")
                
    except Exception as e:
        abi_logging(f"Error getting security status: {e}", level="error")
        raise HTTPException(status_code=500, detail=f"Error getting security status: {str(e)}")

@app.post("/v1/security/block_agent")
async def block_agent(request: dict):
    """Block an agent via Guardian"""
    try:
        agent_id = request.get("agent_id", "")
        reason = request.get("reason", "Manual block via API")
        
        if not agent_id:
            raise HTTPException(status_code=400, detail="agent_id is required")
        
        import httpx
        async with httpx.AsyncClient() as client:
            response = await client.post(
                f"http://{config.guardian_host}:{config.guardian_port}/v1/tools/block_agent",
                json={"agent_id": agent_id, "reason": reason},
                timeout=10.0
            )
            
            if response.status_code == 200:
                return response.json()
            else:
                raise HTTPException(status_code=response.status_code, detail="Guardian service error")
                
    except HTTPException:
        raise
    except Exception as e:
        abi_logging(f"Error blocking agent: {e}", level="error")
        raise HTTPException(status_code=500, detail=f"Error blocking agent: {str(e)}")


def main():
    """Main entry point"""
    abi_logging(f"🌟 abi swarm starting on {config.agent_host}:{config.agent_port}")
    
    uvicorn.run(
        "main:app",
        host=config.agent_host,
        port=config.agent_port,
        reload=config.debug,
        log_level=config.log_level.lower()
    )

if __name__ == "__main__":
    main()