#!/usr/bin/env python3
"""
abi swarm — Interactive Console

Generated by ABI-Core scaffolding.
Extend this file to customize the TUI for your project.

Usage:
    python console.py
    # or via abi-core:
    abi-core run  (auto-detects this file)

To customize:
    - Override compose() to change the layout
    - Add new commands in on_command_input_command_submitted()
    - Add new widgets from abi_core.tui.widgets or your own
"""

from abi_core.tui.app import AbiConsoleApp


class abiswarmConsole(AbiConsoleApp):
    """Interactive console for abi swarm.

    Inherits the full dashboard: banner, service table, log stream,
    conversation panel, and command input.

    Override any method to customize behavior.
    """

    pass


def main():
    app = abiswarmConsole(
        project_name="abi swarm",
        project_version="1.0.0",
        orchestrator_url="http://localhost:8000",
        ollama_host="http://localhost:11434",
    )
    app.run()


if __name__ == "__main__":
    main()