"""
Configuration for abi swarm
Generated by ABI-Core scaffolding
"""

import os
from typing import Dict, Any

class AbiSwarmConfig:
    """Configuration class for abi swarm"""
    
    def __init__(self):
        # Basic project settings
        self.project_name = "abi swarm"
        self.version = "1.0.0"
        self.description = "ABI Swarm - Self-Building Multi-Agent System"
        
        # ABI Core settings
        self.abi_role = os.getenv('ABI_ROLE', 'ABI Project')
        self.abi_node = os.getenv('ABI_NODE', 'ABI Node')
        
        # Agent settings
        self.agent_host = os.getenv('AGENT_HOST', '0.0.0.0')
        self.agent_port = int(os.getenv('AGENT_PORT', '8000'))
        self.agent_base = os.getenv('AGENT_BASE', f'http://{self.agent_host}:{self.agent_port}')
        
        # Model settings
        self.model_name = os.getenv('MODEL_NAME', 'qwen2.5:3b')
        self.ollama_host = os.getenv('OLLAMA_HOST', 'http://abi-swarm-ollama:11434')
        
        # Security settings
        self.enable_guardial = True
        self.opa_host = os.getenv('OPA_HOST', 'localhost')
        self.opa_port = int(os.getenv('OPA_PORT', '8181'))
        
        # Semantic layer settings
        
        self.semantic_layer_host = os.getenv('SEMANTIC_LAYER_HOST', 'localhost')
        self.semantic_layer_port = int(os.getenv('SEMANTIC_LAYER_PORT', '10100'))
        self.weaviate_url = os.getenv('WEAVIATE_URL', 'http://localhost:8080')
        self.embedding_model = os.getenv('EMBEDDING_MODEL', 'nomic-embed-text:v1.5')
        self.agent_cards_dir = os.getenv('AGENT_CARDS_DIR', './services/semantic_layer/mcp_server/agent_cards')
        
        
        # Guardian security settings
        
        self.guardian_host = os.getenv('GUARDIAN_HOST', 'localhost')
        self.guardian_port = int(os.getenv('GUARDIAN_PORT', '11438'))
        self.max_risk_threshold = float(os.getenv('MAX_RISK_THRESHOLD', '0.7'))
        self.emergency_log_dir = os.getenv('EMERGENCY_LOG_DIR', './logs/emergency')
        
        
        # Domain-specific settings
        self.domain = "general"
        
        
        # Logging settings
        self.log_level = os.getenv('LOG_LEVEL', 'INFO')
        self.debug = os.getenv('DEBUG', 'true').lower() == 'true'
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert config to dictionary"""
        return {
            'project_name': self.project_name,
            'version': self.version,
            'description': self.description,
            'abi_role': self.abi_role,
            'abi_node': self.abi_node,
            'agent_host': self.agent_host,
            'agent_port': self.agent_port,
            'agent_base': self.agent_base,
            'model_name': self.model_name,
            'ollama_host': self.ollama_host,
            'enable_guardial': self.enable_guardial,
            'opa_host': self.opa_host,
            'opa_port': self.opa_port,
            
            'semantic_layer_host': self.semantic_layer_host,
            'semantic_layer_port': self.semantic_layer_port,
            'weaviate_url': self.weaviate_url,
            'embedding_model': self.embedding_model,
            'agent_cards_dir': self.agent_cards_dir,
            
            
            'guardian_host': self.guardian_host,
            'guardian_port': self.guardian_port,
            'max_risk_threshold': self.max_risk_threshold,
            'emergency_log_dir': self.emergency_log_dir,
            
            'domain': self.domain,
            
            'log_level': self.log_level,
            'debug': self.debug
        }

# Global config instance
config = AbiSwarmConfig()